### ISSUE TITLE
not issue sorry* How can i export a modpack from BCUPC to BCUANDROID

### ISSUE THREAD

**Issue by ModGamerBackup** [battlecatsultimate/BCU_Android#2]
idk how pls help

**Comment by ModGamerBackup** [comment]
how does your discord read minds

**Comment by MandarinSmell** [comment]
We are explaining only with 0-5-x-x, aka v5 in PC, and 0.15.x, aka 0.15 series in Android.

1. Once you made pack, go to pack managemant page, select your pack, and click export
2. pack.bcuzip file will be created in folder called `exports`. Move that folder to your phone device via cloud, USB, etc
3. Open BCU Android, click button called `Packs` in main menu
4. Click import button in right upper corner in pack managing screen. File picker will appear
5. Pick pack file from file picker, then app will automatically import pack.

I will close issue because explanation is obvious enough. Don't reopen this issue, or open another new issue about this

**Comment by MrbeegamerGitHub** [comment]
dude that is very cringe when I look at the first 2 lines..
