### ISSUE TITLE
Can't load packs from newer versions of BCU PC

### ISSUE THREAD

**Issue by MrNooberDude** [battlecatsultimate/BCU_Android#9]
I made a pack for bcu on my PC that I was hoping to use on my phone. Turns out it isn't recognized as a bcuzip. I have exported them multiple times and it doesn't load. The start of the file's binary looks relatively the same to an older pack, but I'm not smart enough to tell what it means so...
Is there anything I could do here or is this bigger than me just doing something wrong?

**Comment by MandarinSmell** [comment]
Keep in mind that file name must end with `pack.bcuzip` **including extension**. This means that even though actual extension is .bcuzip, **you have to keep .pack at the end of the name too**.

- abcdefg.pack.bcuzip : Valid
- Custom Name.pack.bcuzip : Valid
- abcdefg.bcuzip : Invalid
- abcdefg.pack (1).bcuzip : Invalid

Check if pack file's name is valid. If it turned out to be valid, yet app fails to import pack, please describe what app says. It should lead you to other screen, or it should say some messages

**Comment by MrNooberDude** [comment]
Ohhh, that makes sense! I have screwed up when renaming things. Thanks!
